import './globals.css'
import { Inter } from 'next/font/google'
import Header from  "@/app/components/layout/Header"
import Footer from "@/app/components/layout/footer"
import Providers from './components/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <Header/>
        
        <main className='px-8 md:px-28'>{children}</main>
        </Providers>
        <Footer/>
        </body>
    </html>
  )
}
